### ISSUE TITLE
"Org Billing Manager" role gets removed when editing the unique user with that role.

### ISSUE THREAD

**Issue by keymon** [alphagov/paas-admin#102]
# Summary

When a org has only one user with "Org Billing Manager", if you click on edit the user and then save, the role gets remove without reason.

# Expected result

The role should remain unless un-tick

# How to reproduce:

 1. Given an empty org with no bill managers
 2. Add a new user with "Org Bill manager"
 3. Go back to edit users and click on the new user. The checkbox of "Org Billing Manager" appears as grey and can not be changed.
 4. Click on save user.
 5. Go back to the user, the "Org Billing Manager" role is gone

**Comment by paroxp** [comment]
Fixed in #511
