### ISSUE TITLE
A user with global auditing can reach the "user details" page but it would fail

### ISSUE THREAD

**Issue by keymon** [alphagov/paas-admin#103]
# What?

A user with Global Auditor role in a CF installation can go to an org, see all the org users, and then click on any of these users. But when displaying the user page, it fails.

# Expected

The auditor should not be able to "click" on the user details if it has no permissions, or a more informative error should be displayed.

**Comment by 46bit** [comment]
Should be fixed by #882. Global Auditors still can't see the user page and still get linked to it, but they get a useful error message.
