### ISSUE TITLE
`npm run push`

### ISSUE THREAD

**Issue by henrytk** [alphagov/paas-admin#115]
`npm run push` fails with:

```
Pushing from manifest to org admin / space public as admin...
Using manifest file /Users/henryknott/dev/go/src/github.com/alphagov/paas-admin/manifest.yml
Getting app info...
No app files found in '/Users/henryknott/dev/go/src/github.com/alphagov/paas-admin'
```

I haven't had time to investigate why, but just recording it here.

**Comment by tlwr** [comment]
I regularly run `npm run push` and I have yet to experience this.

I'm going to close it and we can re-open if the problem re-occurs
