### ISSUE TITLE
Jest leaks memory catastrophically  

### ISSUE THREAD

**Issue by 0atman** [alphagov/paas-admin#1666]
![jest](https://user-images.githubusercontent.com/114097/125645592-c7e766bf-8b5c-4f87-8d69-0aaac1f56240.png)

my memory useage goes from 4GB up to my computer's limit of 16GB and then eats all the swap space (2GB) and then my machine freezes up
![Screenshot from 2021-07-14 13-51-26](https://user-images.githubusercontent.com/114097/125645609-132f98a4-44c2-4de8-8925-06e8e3db90f5.png)

More reading:
- https://chanind.github.io/javascript/2019/10/12/jest-tests-memory-leak.html
- https://github.com/kulshekhar/ts-jest/issues/1967

**Comment by kr8n3r** [comment]
we no longer use Jest
